name: SosisAdminJail
version: 2.3.9
main: dev.sosis.adminjail.SosisAdminjailPlugin
api-version: '1.13'
author: ["_Hosseinhg5845_"]

commands:
  adminjail:
    description: Jail a player.
    usage: /adminjail <player> <blocks> [jailname] [reason]
    permission: adminjail.use
  unjail:
    description: Unjail a player.
    usage: /unjail <player>
    permission: adminjail.use
  adminjailadmin:
    description: Central admin command.
    usage: /adminjailadmin <subcommand>
    permission: adminjail.admin
  jailpay:
    description: Pay to complete your jail sentence.
    usage: /jailpay
    permission: adminjail.use
  adminjailstats:
    description: View player jail stats.
    usage: /adminjailstats <player>
    permission: adminjail.use

permissions:
  adminjail.use:
    default: op
  adminjail.admin:
    default: op
    children:
      adminjail.use: true